---
- name: Deploy built files to web server
  hosts: koumakan
  remote_user: deploy
  gather_facts: false

  tasks:
      - name: Copy built files to the destination
        ansible.posix.synchronize:
            src: ../build/
            dest: /srv/www/2024-sba-mockup

    #   - name: Set correct file permissions
    #     ansible.builtin.file:
    #         path: /srv/www/static/
    #         recurse: true
    #         mode: g-wx,o-wx
